server:
  port: 9001

spring:
  application:
    name: cloudalibaba-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
      lettuce:
        shutdown-timeout: 0


management:
  endpoints:
    web:
      exposure:
        include: '*'
